/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ListPropertyRouteImport } from './routes/list-property'
import { Route as HotelsRouteImport } from './routes/hotels'
import { Route as FlightsRouteImport } from './routes/flights'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToursIndexRouteImport } from './routes/tours.index'
import { Route as HotelsIndexRouteImport } from './routes/hotels.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ToursTourIdRouteImport } from './routes/tours.$tourId'
import { Route as HotelsHotelIdRouteImport } from './routes/hotels.$hotelId'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as BookingTourIdRouteImport } from './routes/booking.$tourId'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminToursRouteImport } from './routes/admin.tours'
import { Route as AdminPromosRouteImport } from './routes/admin.promos'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminHotelsRouteImport } from './routes/admin.hotels'
import { Route as AdminFlightsRouteImport } from './routes/admin.flights'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as BookingHotelHotelIdRouteImport } from './routes/booking.hotel.$hotelId'
import { Route as BookingFlightFlightIdRouteImport } from './routes/booking.flight.$flightId'
import { Route as ApiPublicPaymentCallbackRouteImport } from './routes/api/public/payment-callback'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ListPropertyRoute = ListPropertyRouteImport.update({
  id: '/list-property',
  path: '/list-property',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsRoute = HotelsRouteImport.update({
  id: '/hotels',
  path: '/hotels',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightsRoute = FlightsRouteImport.update({
  id: '/flights',
  path: '/flights',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursIndexRoute = ToursIndexRouteImport.update({
  id: '/tours/',
  path: '/tours/',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsIndexRoute = HotelsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HotelsRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ToursTourIdRoute = ToursTourIdRouteImport.update({
  id: '/tours/$tourId',
  path: '/tours/$tourId',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsHotelIdRoute = HotelsHotelIdRouteImport.update({
  id: '/$hotelId',
  path: '/$hotelId',
  getParentRoute: () => HotelsRoute,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingTourIdRoute = BookingTourIdRouteImport.update({
  id: '/booking/$tourId',
  path: '/booking/$tourId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminToursRoute = AdminToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromosRoute = AdminPromosRouteImport.update({
  id: '/promos',
  path: '/promos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHotelsRoute = AdminHotelsRouteImport.update({
  id: '/hotels',
  path: '/hotels',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFlightsRoute = AdminFlightsRouteImport.update({
  id: '/flights',
  path: '/flights',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingHotelHotelIdRoute = BookingHotelHotelIdRouteImport.update({
  id: '/booking/hotel/$hotelId',
  path: '/booking/hotel/$hotelId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingFlightFlightIdRoute = BookingFlightFlightIdRouteImport.update({
  id: '/booking/flight/$flightId',
  path: '/booking/flight/$flightId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentCallbackRoute =
  ApiPublicPaymentCallbackRouteImport.update({
    id: '/api/public/payment-callback',
    path: '/api/public/payment-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/flights': typeof FlightsRoute
  '/hotels': typeof HotelsRouteWithChildren
  '/list-property': typeof ListPropertyRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/flights': typeof AdminFlightsRoute
  '/admin/hotels': typeof AdminHotelsRoute
  '/admin/promos': typeof AdminPromosRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/tours': typeof AdminToursRoute
  '/admin/users': typeof AdminUsersRoute
  '/booking/$tourId': typeof BookingTourIdRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/hotels/$hotelId': typeof HotelsHotelIdRoute
  '/tours/$tourId': typeof ToursTourIdRoute
  '/admin/': typeof AdminIndexRoute
  '/hotels/': typeof HotelsIndexRoute
  '/tours/': typeof ToursIndexRoute
  '/api/public/payment-callback': typeof ApiPublicPaymentCallbackRoute
  '/booking/flight/$flightId': typeof BookingFlightFlightIdRoute
  '/booking/hotel/$hotelId': typeof BookingHotelHotelIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/flights': typeof FlightsRoute
  '/list-property': typeof ListPropertyRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/flights': typeof AdminFlightsRoute
  '/admin/hotels': typeof AdminHotelsRoute
  '/admin/promos': typeof AdminPromosRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/tours': typeof AdminToursRoute
  '/admin/users': typeof AdminUsersRoute
  '/booking/$tourId': typeof BookingTourIdRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/hotels/$hotelId': typeof HotelsHotelIdRoute
  '/tours/$tourId': typeof ToursTourIdRoute
  '/admin': typeof AdminIndexRoute
  '/hotels': typeof HotelsIndexRoute
  '/tours': typeof ToursIndexRoute
  '/api/public/payment-callback': typeof ApiPublicPaymentCallbackRoute
  '/booking/flight/$flightId': typeof BookingFlightFlightIdRoute
  '/booking/hotel/$hotelId': typeof BookingHotelHotelIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/flights': typeof FlightsRoute
  '/hotels': typeof HotelsRouteWithChildren
  '/list-property': typeof ListPropertyRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/flights': typeof AdminFlightsRoute
  '/admin/hotels': typeof AdminHotelsRoute
  '/admin/promos': typeof AdminPromosRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/tours': typeof AdminToursRoute
  '/admin/users': typeof AdminUsersRoute
  '/booking/$tourId': typeof BookingTourIdRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/hotels/$hotelId': typeof HotelsHotelIdRoute
  '/tours/$tourId': typeof ToursTourIdRoute
  '/admin/': typeof AdminIndexRoute
  '/hotels/': typeof HotelsIndexRoute
  '/tours/': typeof ToursIndexRoute
  '/api/public/payment-callback': typeof ApiPublicPaymentCallbackRoute
  '/booking/flight/$flightId': typeof BookingFlightFlightIdRoute
  '/booking/hotel/$hotelId': typeof BookingHotelHotelIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/flights'
    | '/hotels'
    | '/list-property'
    | '/login'
    | '/profile'
    | '/register'
    | '/unsubscribe'
    | '/admin/bookings'
    | '/admin/flights'
    | '/admin/hotels'
    | '/admin/promos'
    | '/admin/content'
    | '/admin/tours'
    | '/admin/users'
    | '/booking/$tourId'
    | '/email/unsubscribe'
    | '/hotels/$hotelId'
    | '/tours/$tourId'
    | '/admin/'
    | '/hotels/'
    | '/tours/'
    | '/api/public/payment-callback'
    | '/booking/flight/$flightId'
    | '/booking/hotel/$hotelId'
    | '/lovable/email/suppression'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/flights'
    | '/list-property'
    | '/login'
    | '/profile'
    | '/register'
    | '/unsubscribe'
    | '/admin/bookings'
    | '/admin/flights'
    | '/admin/hotels'
    | '/admin/promos'
    | '/admin/content'
    | '/admin/tours'
    | '/admin/users'
    | '/booking/$tourId'
    | '/email/unsubscribe'
    | '/hotels/$hotelId'
    | '/tours/$tourId'
    | '/admin'
    | '/hotels'
    | '/tours'
    | '/api/public/payment-callback'
    | '/booking/flight/$flightId'
    | '/booking/hotel/$hotelId'
    | '/lovable/email/suppression'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/flights'
    | '/hotels'
    | '/list-property'
    | '/login'
    | '/profile'
    | '/register'
    | '/unsubscribe'
    | '/admin/bookings'
    | '/admin/flights'
    | '/admin/hotels'
    | '/admin/promos'
    | '/admin/content'
    | '/admin/tours'
    | '/admin/users'
    | '/booking/$tourId'
    | '/email/unsubscribe'
    | '/hotels/$hotelId'
    | '/tours/$tourId'
    | '/admin/'
    | '/hotels/'
    | '/tours/'
    | '/api/public/payment-callback'
    | '/booking/flight/$flightId'
    | '/booking/hotel/$hotelId'
    | '/lovable/email/suppression'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  FlightsRoute: typeof FlightsRoute
  HotelsRoute: typeof HotelsRouteWithChildren
  ListPropertyRoute: typeof ListPropertyRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  BookingTourIdRoute: typeof BookingTourIdRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  ToursTourIdRoute: typeof ToursTourIdRoute
  ToursIndexRoute: typeof ToursIndexRoute
  ApiPublicPaymentCallbackRoute: typeof ApiPublicPaymentCallbackRoute
  BookingFlightFlightIdRoute: typeof BookingFlightFlightIdRoute
  BookingHotelHotelIdRoute: typeof BookingHotelHotelIdRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list-property': {
      id: '/list-property'
      path: '/list-property'
      fullPath: '/list-property'
      preLoaderRoute: typeof ListPropertyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels': {
      id: '/hotels'
      path: '/hotels'
      fullPath: '/hotels'
      preLoaderRoute: typeof HotelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flights': {
      id: '/flights'
      path: '/flights'
      fullPath: '/flights'
      preLoaderRoute: typeof FlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/': {
      id: '/tours/'
      path: '/tours'
      fullPath: '/tours/'
      preLoaderRoute: typeof ToursIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/': {
      id: '/hotels/'
      path: '/'
      fullPath: '/hotels/'
      preLoaderRoute: typeof HotelsIndexRouteImport
      parentRoute: typeof HotelsRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tours/$tourId': {
      id: '/tours/$tourId'
      path: '/tours/$tourId'
      fullPath: '/tours/$tourId'
      preLoaderRoute: typeof ToursTourIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/$hotelId': {
      id: '/hotels/$hotelId'
      path: '/$hotelId'
      fullPath: '/hotels/$hotelId'
      preLoaderRoute: typeof HotelsHotelIdRouteImport
      parentRoute: typeof HotelsRoute
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$tourId': {
      id: '/booking/$tourId'
      path: '/booking/$tourId'
      fullPath: '/booking/$tourId'
      preLoaderRoute: typeof BookingTourIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tours': {
      id: '/admin/tours'
      path: '/tours'
      fullPath: '/admin/tours'
      preLoaderRoute: typeof AdminToursRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/promos': {
      id: '/admin/promos'
      path: '/promos'
      fullPath: '/admin/promos'
      preLoaderRoute: typeof AdminPromosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hotels': {
      id: '/admin/hotels'
      path: '/hotels'
      fullPath: '/admin/hotels'
      preLoaderRoute: typeof AdminHotelsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/flights': {
      id: '/admin/flights'
      path: '/flights'
      fullPath: '/admin/flights'
      preLoaderRoute: typeof AdminFlightsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/hotel/$hotelId': {
      id: '/booking/hotel/$hotelId'
      path: '/booking/hotel/$hotelId'
      fullPath: '/booking/hotel/$hotelId'
      preLoaderRoute: typeof BookingHotelHotelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/flight/$flightId': {
      id: '/booking/flight/$flightId'
      path: '/booking/flight/$flightId'
      fullPath: '/booking/flight/$flightId'
      preLoaderRoute: typeof BookingFlightFlightIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payment-callback': {
      id: '/api/public/payment-callback'
      path: '/api/public/payment-callback'
      fullPath: '/api/public/payment-callback'
      preLoaderRoute: typeof ApiPublicPaymentCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminFlightsRoute: typeof AdminFlightsRoute
  AdminHotelsRoute: typeof AdminHotelsRoute
  AdminPromosRoute: typeof AdminPromosRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminToursRoute: typeof AdminToursRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBookingsRoute: AdminBookingsRoute,
  AdminFlightsRoute: AdminFlightsRoute,
  AdminHotelsRoute: AdminHotelsRoute,
  AdminPromosRoute: AdminPromosRoute,
  AdminContentRoute: AdminContentRoute,
  AdminToursRoute: AdminToursRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface HotelsRouteChildren {
  HotelsHotelIdRoute: typeof HotelsHotelIdRoute
  HotelsIndexRoute: typeof HotelsIndexRoute
}

const HotelsRouteChildren: HotelsRouteChildren = {
  HotelsHotelIdRoute: HotelsHotelIdRoute,
  HotelsIndexRoute: HotelsIndexRoute,
}

const HotelsRouteWithChildren =
  HotelsRoute._addFileChildren(HotelsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  FlightsRoute: FlightsRoute,
  HotelsRoute: HotelsRouteWithChildren,
  ListPropertyRoute: ListPropertyRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  BookingTourIdRoute: BookingTourIdRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  ToursTourIdRoute: ToursTourIdRoute,
  ToursIndexRoute: ToursIndexRoute,
  ApiPublicPaymentCallbackRoute: ApiPublicPaymentCallbackRoute,
  BookingFlightFlightIdRoute: BookingFlightFlightIdRoute,
  BookingHotelHotelIdRoute: BookingHotelHotelIdRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
